export const memo = {
    // SECTION A Answers
    '1.1.1': { answer: 'B', marks: 1 },
    '1.1.2': { answer: 'A', marks: 1 },
    '1.1.3': { answer: 'C', marks: 1 },
    '1.1.4': { answer: 'A', marks: 1 },
    '1.1.5': { answer: 'B', marks: 1 },
    '1.1.6': { answer: 'C', marks: 1 },
    '1.1.7': { answer: 'B', marks: 1 },
    '1.1.8': { answer: 'C', marks: 1 },
    '1.1.9': { answer: 'B', marks: 1 },
    '1.1.10': { answer: 'C', marks: 1 },
    '1.1.11': { answer: 'A', marks: 1 },
    '1.1.12': { answer: 'D', marks: 1 },
    '1.1.13': { answer: 'D', marks: 1 },
    '1.1.14': { answer: 'A', marks: 1 },
    '1.1.15': { answer: 'D', marks: 1 },
    '1.1.16': { answer: 'A', marks: 1 },
    '1.1.17': { answer: 'C', marks: 1 },
    '1.1.18': { answer: 'D', marks: 1 },
    '1.1.19': { answer: 'B', marks: 1 },
    '1.1.20': { answer: 'C', marks: 1 },

    '1.2.1': { answer: 'company stationery', marks: 1 },
    '1.2.2': { answer: 'physical appearance of the business', marks: 1 },
    '1.2.3': { answer: 'grooming', marks: 1 },
    '1.2.4': { answer: 'promotes integrity', marks: 1 },
    '1.2.5': { answer: 'uniform allowances', marks: 1 },

    '1.3.1': { answer: 're-using', marks: 1 },
    '1.3.2': { answer: 'management of resources', marks: 1 },
    '1.3.3': { answer: 'alien plants', marks: 1 },
    '1.3.4': { answer: 'grey water', marks: 1 },
    '1.3.5': { answer: 'handmade', marks: 1 },

    '1.4.1': { answer: 'D', marks: 1 },
    '1.4.2': { answer: 'F', marks: 1 },
    '1.4.3': { answer: 'A', marks: 1 },
    '1.4.4': { answer: 'B', marks: 1 },
    '1.4.5': { answer: 'C', marks: 1 },

    '1.5.1': { answer: 'Mapungubwe', marks: 1 },
    '1.5.2': { answer: 'Barberton Makhonjwa Mountains', marks: 1 },
    '1.5.3': { answer: 'iSimangaliso Wetland Park', marks: 1 },
    '1.5.4': { answer: 'Cradle of Humankind', marks: 1 },
    '1.5.5': { answer: 'Robben Island', marks: 1 },

    // SECTION B Answers
    '2.1.1': { answer: 'rebuilding damaged tourism infrastructure', marks: 2 },
    '2.1.2': { answer: 'passport', marks: 2 },
    '2.1.3': { answer: 'World Health Organization', marks: 2 },
    '2.1.4': { answer: 'get necessary vaccinations', marks: 2 },
    '2.2.1': { answer: 'flight with stopover', marks: 2 },
    '2.2.2': { answer: '03:00 Sunday', marks: 4 },
    '2.2.3': { answer: '4 hours', marks: 2 },
    '2.2.4': { answer: '04:00 Monday', marks: 5 },
    '2.3.1': { answer: 'green', marks: 2 },
    '2.3.2': { answer: 'he had nothing to declare', marks: 2 },
    '2.3.3': { answer: 'check licensed vehicle and use registered services', marks: 4 },

    '3.1.1': { answer: 'British Pound', marks: 2 },
    '3.1.2': { answer: '55256', marks: 2 },
    '3.1.3': { answer: '19744', marks: 2 },
    '3.1.4': { answer: 'yes', marks: 4 },
    '3.1.5': { answer: '2706', marks: 3 },
    '3.2.1': { answer: 'continuous change', marks: 2 },
    '3.2.2': { answer: 'makes SA cheaper for international tourists', marks: 6 },

    // Add more answers as needed for other sections
    '4.1.1A': { answer: 'Eiffel Tower', marks: 1 },
    '4.1.1B': { answer: 'Great Wall of China', marks: 1 },
    '4.1.1C': { answer: 'Statue of Liberty', marks: 1 },
    '4.1.1D': { answer: 'Pyramids of Giza', marks: 1 },
    '4.1.1E': { answer: 'Taj Mahal', marks: 1 },
    '4.1.1F': { answer: 'Sydney Opera House', marks: 1 },

    '4.2.1': { answer: 'Japan', marks: 2 },
    '4.2.2': { answer: 'pollution', marks: 2 },
    '4.2.3': { answer: 'waste management and visitor limits', marks: 4 },

    '5.1A': { answer: 'Richtersveld Cultural and Botanical Landscape', marks: 2 },
    '5.1B': { answer: 'ǀXam and ǀKhomani Heartland', marks: 2 },
    '5.2.1': { answer: 'cultural preservation', marks: 2 },
    '5.2.2': { answer: 'rock art tours', marks: 2 },
    '5.3': { answer: 'job creation', marks: 2 },

    '6.1': { answer: 'marketing event for travel industry', marks: 2 },
    '6.2': { answer: 'Indaba', marks: 2 },
    '6.3': { answer: 'funding marketing campaigns', marks: 6 },

    '7.1.1': { answer: 'quick response', marks: 2 },
    '7.1.2': { answer: 'professional communication', marks: 4 },
    '7.2.1': { answer: 'fair salary and legal deductions', marks: 4 },
    '7.2.2': { answer: 'regular hours vs extra hours', marks: 4 },

    '8.1': { answer: 'education and infrastructure', marks: 4 },
    '8.2': { answer: 'economic and environmental', marks: 4 },
    '8.3': { answer: 'job creation and local procurement', marks: 4 },
    '8.4': { answer: 'supports local communities', marks: 4 },

    '9.1.1': { answer: 'Northern', marks: 2 },
    '9.1.2': { answer: 'fuel prices and wheat prices', marks: 4 },
    '9.1.3': { answer: 'higher costs and limited supplies', marks: 6 },
    '9.2.1': { answer: 'Gauteng, Western Cape, Mpumalanga', marks: 2 },
    '9.2.2': { answer: 'limited attractions', marks: 2 },

    '10.1': { answer: 'improve service quality', marks: 2 },
    '10.2': { answer: 'friendly staff', marks: 2 },
    '10.3': { answer: 'high satisfaction ratings', marks: 4 },
    '10.4': { answer: 'menu variety improvement', marks: 2 },
};