export const performanceData = [
    {
        learnerId: 'L001',
        name: 'John Doe',
        subject: 'Math',
        activityType: 'Quiz',
        activityName: 'Algebra Quiz 1',
        date: '2025-06-01',
        score: 85,
        maxScore: 100,
        timeSpent: 30,
        difficulty: 'Medium',
        status: 'Passed',
        comments: 'Strong grasp of equations',
    },
    // Add remaining data entries (as in the original HTML)...
    {
        learnerId: 'L007',
        name: 'Liam Wilson',
        subject: 'Computer Science',
        activityType: 'Quiz',
        activityName: 'Python Basics Quiz',
        date: '2025-06-08',
        score: 90,
        maxScore: 100,
        timeSpent: 25,
        difficulty: 'Medium',
        status: 'Passed',
        comments: 'Strong programming skills',
    },
];