export const correctAnswers = {
    // Section A
    "q1.1.1": "B",
    "q1.1.2": "A",
    "q1.1.3": "C",
    "q1.1.4": "B",
    "q1.1.5": "B",
    "q1.1.6": "D",
    "q1.1.7": "B",
    "q1.1.8": "A",
    "q1.1.9": "C",
    "q1.1.10": "B",
    "q1.1.11": "A",
    "q1.1.12": "A",
    "q1.1.13": "B",
    "q1.1.14": "B",
    "q1.1.15": "A",
    "q1.1.16": "D",
    "q1.1.17": "B",
    "q1.1.18": "C",
    "q1.1.19": "B",
    "q1.1.20": "C",
    "q1.2.1": "political",
    "q1.2.2": "recession",
    "q1.2.3": "money spent",
    "q1.2.4": "publicity",
    "q1.2.5": "land",
    "q1.3.1": "reduced",
    "q1.3.2": "FTT",
    "q1.3.3": "CSI",
    "q1.3.4": "glass",
    "q1.3.5": "the triple bottom-line",
    "q1.4.1": "Mapungubwe Cultural Landscape",
    "q1.4.2": "Vredefort Dome",
    "q1.4.3": "Barberton Makhonjwa Mountains",
    "q1.4.4": "iSimangaliso Wetland Park",
    "q1.4.5": "Fossil Hominid Sites of South Africa",
    "q1.5.1": "H",
    "q1.5.2": "B",
    "q1.5.3": "G",
    "q1.5.4": "E",
    "q1.5.5": "D",

    "q2.1.1": "1 hour",
    "q2.1.2_time": "07:00",
    "q2.1.2_date": "19 July 2024",
    "q2.1.3": "The team had to adjust their watches ONE hour forward",
    "q2.1.4a": "Jet fatigue",
    "q2.1.4b": "It was a flight that did not cross many time zones",
    "q2.2.1": "Schengen visa",
    "q2.2.2": "France was the first point of entry into Europe",
    "q2.2.3": "This visa grants access to all the countries to be visited",
    "q2.3.1": "Passports and money",
    "q2.3.2": "Take personal responsibility against sun exposure. Use sunblock with a high sun protection factor. Wear protective hats/clothing/sunglasses.",
    "q2.3.3": "Do not walk alone and avoid poorly lit areas",
    "q2.4": "He carried items that needed to be declared and the items exceeded the duty-free allowances",

    // Section B
    "q3.1.1": "GBP",
    "q3.1.2": "EUR",
    "q3.2": 2433.09,
    "q3.3": 1539.00,
    "q3.4.1": "Gross Domestic Product is a measure of all the goods and services produced domestically over a specific time",
    "q3.4.2": "The Olympic Games brought many tourists to France, resulting in an increase in foreign income earnings",

    // Section C
    "q4.1.1a": "The Statue of Christ the Redeemer, The Great Pyramids of Giza, Ayers Rock/Uluru, Sydney Opera House",
    "q4.1.1b": "Brazil, Egypt, Australia, Australia",
    "q4.1.2a": "Sydney Opera House",
    "q4.1.2b": "Operas and music concerts/shows are held in the building",
    "q4.1.3": "The Great Pyramids of Giza are located on the outskirts of Giza, Egypt. They were built more than 1,200 years before King Tutankhamen. They were built as tombs for the pharaohs.",
    "q4.1.4": "The Statue of Christ the Redeemer has become a symbolic protector of people. Uluru is a sacred place for the indigenous people.",
    "q4.2.1a": "Colosseum",
    "q4.2.1b": "Leaning Tower of Pisa",
    "q4.2.1c": "Venice",
    "q4.2.2": "Colosseum: Ancient building with a large amphitheatre. Leaning Tower of Pisa: It is leaning because it was built on unstable soil. Venice: City built on water with bridges and canals.",

    // Section D
    "q5.1a": "Robben Island",
    "q5.1b": "Cape Floral Region Protected Areas",
    "q5.2": "Nelson Mandela was imprisoned at Robben Island as a political prisoner. Robben Island served as South Africa's maximum-security political prison.",
    "q5.3": "UNESCO seeks to encourage the identification of global sites of outstanding value to humanity.",
    "q6.1.1": "He is a well-known rugby player and the captain of the Springbok rugby team.",
    "q6.1.2": "To increase the annual volume of foreign arrivals to SA and to increase international awareness of South Africa as a destination of choice.",
    "q6.2.1": "ITB",
    "q6.2.2": "TOMSA collects the 1% levy from the contributors, hands it to TBCSA who administers it. The funds are made available to SATourism for international marketing.",

    "q7.1.1": "contract of employment",
    "q7.1.2a": "9 hours per day",
    "q7.1.2b": "Lydia must be paid 1.5 times the regular rate for hours worked",
    "q7.2.1": "The code of conduct will regulate how staff should behave while working on a cruise ship",
    "q7.2.2": "If a crew member does not show respect for cultural differences, they could face disciplinary action",
    "q7.2.3": "Respecting the code of conduct encourages teamwork by setting clear rules for behaviour",
    "q8.1.1": "Solar power uses sunlight to generate electricity",
    "q8.1.2a": "Environmental",
    "q8.1.2b": "Social and Economic",
    "q8.1.3": "It reduces the impact on the environment and solar power is generated from sunlight and is a renewable resource",
    "q8.2.1": "Reduces the business' reliance on fossil fuels through sustainable practices and business operations can be cost-effective",
    "q8.2.2": "Airports can use efficient technology that supports green initiatives and use alternative fuels and electric vehicles",

    // Section E
    "q9.1.1": "summit",
    "q9.1.2": "South Africa can develop trade relations with oil rich nations and these countries can assist in decreasing South Africa's reliance on fossil fuel sources",
    "q9.2.1": "Flooding",
    "q9.2.2a": "Damage to water treatment facilities can lead to contamination of drinking water sources",
    "q9.2.2b": "Damage to infrastructure can delay emergency response efforts",
    "q9.3.1": "The need for actual cards is eliminated and digital wallets allow for contactless and paperless payments globally",
    "q9.3.2": "Using cash has become a security concern with the risk of theft and once lost it cannot be replaced",
    "q10.1": "A customer survey is a method of collecting customer feedback",
    "q10.2": "Analyse and capture the feedback to determine the level of service and group all the common complaints to identify the problem areas",
    "q10.3": "Analysing the survey responses will assist the company in improving service delivery and the findings will assist in developing an action plan to correct products and services"
};

export const questionWeights = {
    "q1.1.1": 1, "q1.1.2": 1, "q1.1.3": 1, "q1.1.4": 1, "q1.1.5": 1,
    "q1.1.6": 1, "q1.1.7": 1, "q1.1.8": 1, "q1.1.9": 1, "q1.1.10": 1,
    "q1.1.11": 1, "q1.1.12": 1, "q1.1.13": 1, "q1.1.14": 1, "q1.1.15": 1,
    "q1.1.16": 1, "q1.1.17": 1, "q1.1.18": 1, "q1.1.19": 1, "q1.1.20": 1,
    "q1.2.1": 1, "q1.2.2": 1, "q1.2.3": 1, "q1.2.4": 1, "q1.2.5": 1,
    "q1.3.1": 1, "q1.3.2": 1, "q1.3.3": 1, "q1.3.4": 1, "q1.3.5": 1,
    "q1.4.1": 1, "q1.4.2": 1, "q1.4.3": 1, "q1.4.4": 1, "q1.4.5": 1,
    "q1.5.1": 1, "q1.5.2": 1, "q1.5.3": 1, "q1.5.4": 1, "q1.5.5": 1,

    "q2.1.1": 2, "q2.1.2_time": 2, "q2.1.2_date": 2, "q2.1.3": 2,
    "q2.1.4a": 2, "q2.1.4b": 2, "q2.2.1": 1, "q2.2.2": 2, "q2.2.3": 4,
    "q2.3.1": 2, "q2.3.2": 6, "q2.3.3": 4, "q2.4": 4,
    "q3.1.1": 1, "q3.1.2": 1, "q3.2": 3, "q3.3": 3, "q3.4.1": 2, "q3.4.2": 4,

    "q4.1.1a": 4, "q4.1.1b": 3, "q4.1.2a": 2, "q4.1.2b": 2, "q4.1.3": 6,
    "q4.1.4": 4, "q4.2.1a": 1, "q4.2.1b": 1, "q4.2.1c": 1, "q4.2.2": 6,
    "q5.1a": 2, "q5.1b": 2, "q5.2": 4, "q5.3": 2,
    "q6.1.1": 2, "q6.1.2": 4, "q6.2.1": 2, "q6.2.2": 2,

    "q7.1.1": 2, "q7.1.2a": 2, "q7.1.2b": 2, "q7.2.1": 2, "q7.2.2": 2, "q7.2.3": 2,
    "q8.1.1": 2, "q8.1.2a": 2, "q8.1.2b": 2, "q8.1.3": 4, "q8.2.1": 4, "q8.2.2": 4,

    "q9.1.1": 2, "q9.1.2": 4, "q9.2.1": 2, "q9.2.2a": 2, "q9.2.2b": 2,
    "q9.3.1": 4, "q9.3.2": 4,
    "q10.1": 2, "q10.2": 4, "q10.3": 4
};