import React, { useState } from 'react';
import ReactDOM from 'react-dom/client';

const answerKey = {
    'q1-1-1': ['b'],
    'q1-1-2': ['a'],
    'q1-1-3': ['c'],
    'q1-1-4': ['b'],
    'q1-1-5': ['b'],
    'q1-1-6': ['c'],
    'q1-1-7': ['b'],
    'q1-1-8': ['c'],
    'q1-1-9': ['b'],
    'q1-1-10': ['d'],
    'q1-1-11': ['a'],
    'q1-1-12': ['d'],
    'q1-1-13': ['d'],
    'q1-1-14': ['a'],
    'q1-1-15': ['d'],
    'q1-1-16': ['a'],
    'q1-1-17': ['c'],
    'q1-1-18': ['d'],
    'q1-1-19': ['b'],
    'q1-1-20': ['c'],
    'q1-2-1': ['company stationery'],
    'q1-2-2': ['physical appearance of the business'],
    'q1-2-3': ['grooming'],
    'q1-2-4': ['promotes integrity'],
    'q1-2-5': ['uniform allowances'],
    'q1-3-1': ['re-using'],
    'q1-3-2': ['management of resources'],
    'q1-3-3': ['alien plants'],
    'q1-3-4': ['grey water'],
    'q1-3-5': ['handmade'],
    'q1-4-1': ['d'],
    'q1-4-2': ['f'],
    'q1-4-3': ['a'],
    'q1-4-4': ['b'],
    'q1-4-5': ['c'],
    'q1-5-1': ['mapungubwe cultural landscape'],
    'q1-5-2': ['barberton makhonjwa mountains'],
    'q1-5-3': ['maloti-drakensberg park', 'ukhahlamba-drakensberg park'],
    'q1-5-4': ['cradle of humankind', 'fossil hominid sites of south africa', 'maropeng'],
    'q1-5-5': ['robben island'],
    'q2-1-1': ['he spends time in a flood-affected area to assist the community in rebuilding the tourism infrastructure', 'he wants to make a positive social impact by spending time assisting the local community', 'he has chosen a destination in need of money that is generated by tourism', 'he is giving back to the community and contributing to the local economy'],
    'q2-1-2': ['passport'],
    'q2-1-3': ['world health organisation', 'who'],
    'q2-1-4': ['drink bottled water', 'wear a mask', 'sanitise regularly', 'advisable to have taken the covid-19 vaccine'],
    'q2-2-1': ['a flight that requires a passenger to change aeroplanes and take another flight to get to his final destination', 'a flight with a stop and a change of aircraft to get to the final destination'],
    'q2-2-2': ['03:00 on sunday'],
    'q2-2-3': ['4 hours'],
    'q2-2-4': ['04:00 on monday'],
    'q2-3-1': ['green channel'],
    'q2-3-2': ['he has nothing to declare', 'the goods mr. murdock brought into the country are within the duty-free limits'],
    'q2-3-3': ['he should use registered transport providers', 'he should get information from the information desk at the airport about registered reputable trustworthy transport providers', 'he should never ask for help from a stranger about transport', 'should mr. murdock make use of the b and bs transport he must ensure beforehand the name of the shuttle company and the contact details of the driver'],
    'q3-1-1': ['great british pound', 'pound sterling', 'british pound'],
    'q3-1-2': ['r55256'],
    'q3-1-3': ['r19744'],
    'q3-1-4': ['yes all her major expenses were paid and there was enough money left for spending to buy souvenirs and go on short trips the duration of her stay in london was only for a period of four days', 'no london is a very expensive city this amount is far too little to spend in london once the rand has been converted into british pound'],
    'q3-1-5': ['gbp2705.97'],
    'q3-2-1': ['fluctuation refers to the daily change of the value of one currency against other currencies', 'fluctuation refers to the rising and falling of the value of currencies over a certain period'],
    'q3-2-2': ['greater influx of inbound international tourists as south africa will be seen as a value for money destination tourists will find south africa an affordable destination to visit', 'more inbound tourists will mean more people would need to be employed in the tourism sector much needed revenue will be generated to rebuild destroyed infrastructure particularly in kwazulu natal more employment will mean that more people become tax payers increased collection of taxes would improve the overall infrastructure lead to less poverty and criminal activities will lead to direct and indirect jobs being created'],
    'q4-1-1a': ['mecca', 'kaabah', 'mosque'],
    'q4-1-1b': ['the parthenon'],
    'q4-1-1c': ['dome of the rock'],
    'q4-1-1d': ['blue mosque'],
    'q4-1-1e': ['eiffel tower'],
    'q4-1-1f': ['taj mahal'],
    'q4-1-2': ['the country is associated with the icon symbolises a country receives millions of tourists per year high revenue generator increased publicity for the icon and the country unique features', 'attract visitors to the area lesser-known by the rest of the world attract fewer tourists'],
    'q4-1-3a': ['the parthenon is ruins of a temple on top of the acropolis a hill in athens it is a building characterised by pillars columns originally built as a temple it was also used as a treasury a fortress a church and a mosque built in honour of the greek goddess athena'],
    'q4-1-3b': ['it is a mosque with an impressive interior design the roof is unique with small domes surrounding the bigger dome there are six minarets small towers at the blue mosque the name comes from the blue ceramic tiles on the inside walls'],
    'q4-1-4a': ['it is a landmark in the city paris it is a symbol of france it is one of the most recognised structures in the world it used to be the tallest structure in the world 324m high the entire tower is built from iron the whole of paris can be seen from the top of the tower there is a radio antenna on top of the tower'],
    'q4-1-4b': ['higher revenue and foreign currency earnings contribution to the countrys gdp increased job creation more entrepreneurial opportunities increased visitor numbers to france'],
    'q4-2-1': ['japan'],
    'q4-2-2': ['extra strain on the resources in the area eg water electricity sanitation damage to the natural environment challenges with access control challenges with management of visitors increased levels of pollution'],
    'q4-2-3': ['litter bins available along the hiking trails hiking trails are well demarcated marked clear signage of where hikers may go educational presentations on the natural resources plants and animals that visitors will see educational presentations on how to preserve nature and the importance of conservation encourage climbers to use the routes out of season to reduce the negative impact of too many visitors charging entrance fees to control crowds restriction on the number of cars entering the area regular clean-up of mountain areas'],
    'q5-1a': ['khomani cultural landscape'],
    'q5-1b': ['richtersveld cultural and botanical landscape'],
    'q5-2-1': ['the culture of the san and nama should be protected for future generations to experience traditions and culture of the san and nama people protection for future generations'],
    'q5-2-2': ['they take tourists on hunting expeditions and show them how to track the animals the visitors are taken on a tour and are exposed to their simple way of living their traditions and culture'],
    'q5-3': ['greater publicity for the province revenue generated can be used to upgrade and maintain the infrastructure financial benefits for the province product owners and service providers decrease in unemployment poverty and crime creates jobs and entrepreneurial opportunities which will improve their standard of living'],
    'q6-1': ['an event where tourism-related businesses are given the opportunity to exhibit and promote their products and services an event where the major role players in the tourism industry can network in order to establish new business relationships an event where buyers such as tour operators can negotiate business deals with exhibitors'],
    'q6-2': ['getaway shows cape town and johannesburg', 'meetings africa johannesburg cape town', 'africas travel indaba kwazulu-natal', 'world travel market wtm cape town'],
    'q6-3': ['participating tourism businesses collect the 1 levy from tourists this money is paid to tomsa on a monthly basis who then makes it available to the tbcsa tbcsa as administrators of the funds then pays the money to satourism'],
    'q7-1-1': ['good communication skills professional interaction with customers prompt responses to comments on social media platforms'],
    'q7-1-2': ['the hotel logo the hotel has a website tangohotelsltd the hotel has social media platforms such as instagram the hotel monitors their social media platforms closely and responds quickly customer services policies are implemented'],
    'q7-2-1': ['the salary is fair payment for the work completed regular payment of monthly salarywage the salary is competitive within the sector working hours meal breaks and overtime comply within the law amounts deducted from the salary eg uif are according to the law paid for overtime'],
    'q7-2-2': ['maximum working hours are specified eg 45 hours per week normal working hours are part of contractual obligation working hours are paid at normal rates', 'hours worked over and above the required working hours overtime hours are negotiated to a maximum of 10 hours per week overtime is paid at a higher rate than ordinary working hours'],
    'q8-1': ['infrastructure education capacity building health sanitation guest contributions'],
    'q8-2': ['economic pillar profit', 'environmental pillar planet'],
    'q8-3': ['local residents are employed by the tourism business the tourism business buys supplies locally or makes use of local services the business procures goods and services from certified fair trade tourism companies'],
    'q8-4': ['it encourage tourists to choose the services of tourism businesses that have been ftt certified it assures tourists that the money that they spend at these establishments will benefit the local community it shows other tourism businesses that tourists prefer to support ftt certified establishments ftt certified companies collaborate to compile and market packages which will appeal to responsible tourists'],
    'q9-1-1': ['northern'],
    'q9-1-2': ['higher fuel price higher petrol price increase in the price of crude oil', 'limited supply of wheat availability of wheat flour increase in bread prices'],
    'q9-1-3': ['increased petrol prices will make long distance travel expensive and unaffordable car hire will be a less popular option because of the cost of petrol busshuttletaxi industry will suffer higher ticket prices and availability of fuel availability frequency cancellations and increased cost of flights and other forms of transport will be affect'],
    'q9-2-1': ['gauteng western cape mpumalanga'],
    'q9-2-2': ['long travel distances from the major gateways of the country limited air accessfewer domestic flights to these provinces these are lesser-known and marketed provinces limited infrastructure to attract major events within the province the attractions are situated far apart from each other'],
    'q10-1': ['the survey will help identify where and how he can improve his business and increase visitor numbers to get a benchmark for incentives for staff to get a sense of how customers regard his business'],
    'q10-2': ['chef and the team'],
    'q10-3': ['the ratings for the chef and the team were the highest the conduct and communication involving frontline staff received low ratings from the customers the cleanliness and maintenance of the restaurant received low ratings the waiters do not take their work seriously'],
    'q10-4': ['re-train and up-skill all frontline staff managers to effectively manage and control staff make the incentive package attractive to staff make a supervisor responsible to control the cleanliness and maintenance of the restaurant do everything in his power to create a memorable experience for guests']
};

const solutions = {
    'q1-1-1': 'Proof of vaccination',
    'q1-1-2': 'items to be declared.',
    'q1-1-3': '8',
    'q1-1-4': 'on a long-haul flight.',
    'q1-1-5': 'higher than',
    'q1-1-6': 'The Wailing Wall',
    'q1-1-7': 'Jordan',
    'q1-1-8': 'a mountain range popular for skiing holidays.',
    'q1-1-9': 'Both are natural sites.',
    'q1-1-10': 'South Africa – Inspiring new ways',
    'q1-1-11': 'dress code',
    'q1-1-12': 'core duties',
    'q1-1-13': 'minimize the impact on the environment.',
    'q1-1-14': 'travel benefit',
    'q1-1-15': 'Wooden walkways are built around existing trees.',
    'q1-1-16': 'global summit',
    'q1-1-17': 'Carrying large amounts of cash',
    'q1-1-18': 'Civil wars',
    'q1-1-19': 'global',
    'q1-1-20': 'unforeseen occurrence',
    'q1-2-1': 'company stationery',
    'q1-2-2': 'physical appearance of the business',
    'q1-2-3': 'grooming',
    'q1-2-4': 'promotes integrity',
    'q1-2-5': 'uniform allowances',
    'q1-3-1': 're-using',
    'q1-3-2': 'management of resources',
    'q1-3-3': 'alien plants',
    'q1-3-4': 'grey water',
    'q1-3-5': 'handmade',
    'q1-4-1': 'KwaZulu-Natal',
    'q1-4-2': 'Eswatini',
    'q1-4-3': 'Philippines',
    'q1-4-4': 'Madagascar',
    'q1-4-5': 'Equador',
    'q1-5-1': 'Mapungubwe Cultural Landscape',
    'q1-5-2': 'Barberton Makhonjwa Mountains',
    'q1-5-3': 'Maloti-Drakensberg Park / uKhahlamba-Drakensberg Park',
    'q1-5-4': 'Cradle of Humankind / Fossil Hominid Sites of South Africa / Maropeng',
    'q1-5-5': 'Robben Island',
    'q2-1-1': 'He spends time in a flood-affected area to assist the community in rebuilding the tourism infrastructure. He wants to make a positive social impact by spending time assisting the local community. He has chosen a destination in need of money that is generated by tourism. He is giving back to the community and contributing to the local economy.',
    'q2-1-2': 'Passport',
    'q2-1-3': 'World Health Organisation / WHO',
    'q2-1-4': 'Drink bottled water. Wear a mask. Sanitise regularly. Advisable to have taken the Covid-19 vaccine',
    'q2-2-1': 'A flight that requires a passenger to change aeroplanes and take another flight to get to his final destination. A flight with a stop and a change of aircraft to get to the final destination.',
    'q2-2-2': 'Vancouver -8. Frankfurt +1. Time difference = 9 hours. 18:00 + 9 hours = 03:00 on Sunday',
    'q2-2-3': 'Arrival at Frankfurt 12:00. Departure to South Africa 16:00. Time in transit = 4 hours',
    'q2-2-4': 'Frankfurt +1. Johannesburg +2. Time difference = 1 hour. 16:00 + 1 hour = 17:00 + 11 hours (flying time) = 04:00 on Monday',
    'q2-3-1': 'Green channel',
    'q2-3-2': 'He has nothing to declare. The goods Mr. Murdock brought into the country are within the duty-free limits.',
    'q2-3-3': 'He should use registered transport providers. He should get information from the information desk at the airport about registered reputable (trustworthy) transport providers. He should never ask for help from a stranger about transport. Should Mr. Murdock make use of the B&B\'s transport, he must ensure beforehand the name of the shuttle company and the contact details of the driver.',
    'q3-1-1': 'Great British Pound / Pound Sterling / British Pound',
    'q3-1-2': 'R13 000 + R2 950 + R1 456 + R37 850 = R55 256',
    'q3-1-3': 'R75 000 - R55 256 = R19 744',
    'q3-1-4': 'Yes / I agree. All her major expenses were paid and there was enough money left for spending to buy souvenirs and go on short trips. The duration of her stay in London was only for a period of four days. OR No / I disagree. London is a very expensive city. This amount is far too little to spend in London once the rand has been converted into British pound.',
    'q3-1-5': 'R55 256 ÷ 20.42 = GBP2 705.97',
    'q3-2-1': 'Fluctuation refers to the daily change of the value of one currency against other currencies. Fluctuation refers to the rising and falling of the value of currencies over a certain period.',
    'q3-2-2': 'Greater influx of inbound international tourists as South Africa will be seen as a value for money destination. Tourists will find South Africa an affordable destination to visit. More inbound tourists will mean more people would need to be employed in the tourism sector. Much needed revenue will be generated to rebuild destroyed infrastructure, particularly in KwaZulu Natal. More employment will mean that more people become tax payers. Increased collection of taxes would improve the overall infrastructure. Lead to less poverty and criminal activities. Will lead to direct and indirect jobs being created.',
    'q4-1-1a': 'Mecca / Kaabah / Mosque',
    'q4-1-1b': 'The Parthenon',
    'q4-1-1c': 'Dome of the Rock',
    'q4-1-1d': 'Blue Mosque',
    'q4-1-1e': 'Eiffel Tower',
    'q4-1-1f': 'Taj Mahal',
    'q4-1-2': 'The country is associated with the icon / Symbolises a country. Receives millions of tourists per year. High revenue generator. Increased publicity for the icon and the country. Unique features. Attract visitors to the area. Lesser-known by the rest of the world. Attract fewer tourists.',
    'q4-1-3a': 'The Parthenon is ruins of a temple on top of the Acropolis, a hill in Athens. It is a building characterised by pillars (columns). Originally built as a temple, it was also used as a treasury, a fortress, a church and a mosque. Built in honour of the Greek goddess Athena.',
    'q4-1-3b': 'It is a mosque with an impressive interior design. The roof is unique with small domes surrounding the bigger dome. There are six minarets (small towers) at the Blue Mosque. The name comes from the blue ceramic tiles on the inside walls.',
    'q4-1-4a': 'It is a landmark in the city, Paris. It is a symbol of France. It is one of the most recognised structures in the world. It used to be the tallest structure in the world – 324m high. The entire tower is built from iron. The whole of Paris can be seen from the top of the tower. There is a radio antenna on top of the tower.',
    'q4-1-4b': 'Higher revenue and foreign currency earnings. Contribution to the country\'s GDP. Increased job creation. More entrepreneurial opportunities. Increased visitor numbers to France.',
    'q4-2-1': 'Japan',
    'q4-2-2': 'Extra strain on the resources in the area e.g. water, electricity, sanitation. Damage to the natural environment. Challenges with access control. Challenges with management of visitors. Increased levels of pollution.',
    'q4-2-3': 'Litter bins available along the hiking trails. Hiking trails are well demarcated (marked). Clear signage of where hikers may go. Educational presentations on the natural resources, plants and animals that visitors will see. Educational presentations on how to preserve nature and the importance of conservation. Encourage climbers to use the routes out of season to reduce the negative impact of too many visitors. Charging entrance fees to control crowds. Restriction on the number of cars entering the area. Regular clean-up of mountain areas.',
    'q5-1a': 'ǂKhomani Cultural Landscape',
    'q5-1b': 'Richtersveld Cultural and Botanical Landscape',
    'q5-2-1': 'The culture of the San and Nama should be protected for future generations to experience traditions and culture of the San and Nama people. Protection for future generations.',
    'q5-2-2': 'They take tourists on hunting expeditions and show them how to track the animals. The visitors are taken on a tour and are exposed to their simple way of living, their traditions and culture.',
    'q5-3': 'Greater publicity for the province. Revenue generated can be used to upgrade and maintain the infrastructure. Financial benefits for the province, product owners and service providers. Decrease in unemployment, poverty and crime. Creates jobs and entrepreneurial opportunities which will improve their standard of living.',
    'q6-1': 'An event where tourism-related businesses are given the opportunity to exhibit and promote their products and services. An event where the major role players in the tourism industry can network in order to establish new business relationships. An event where buyers such as tour operators can negotiate business deals with exhibitors.',
    'q6-2': 'Getaway Shows (Cape Town and Johannesburg). Meetings Africa (Johannesburg / Cape Town). Africa\'s Travel Indaba (KwaZulu-Natal). World Travel Market –WTM (Cape Town).',
    'q6-3': 'Participating tourism businesses collect the 1% levy from tourists. This money is paid to TOMSA on a monthly basis, who then makes it available to the TBCSA. TBCSA as administrators of the funds then pays the money to SATourism.',
    'q7-1-1': 'Good communication skills. Professional interaction with customers. Prompt responses to comments on social media platforms.',
    'q7-1-2': 'The hotel logo. The hotel has a website @TangoHotelsLtd. The hotel has social media platforms such as Instagram. The hotel monitors their social media platforms closely and responds quickly. Customer services policies are implemented.',
    'q7-2-1': 'The salary is fair payment for the work completed. Regular payment of monthly salary/wage. The salary is competitive within the sector. Working hours / meal breaks and overtime comply within the law. Amounts deducted from the salary (e.g. UIF) are according to the law. Paid for overtime.',
    'q7-2-2': 'Working hours: Maximum working hours are specified, e.g. 45 hours per week. Normal working hours are part of contractual obligation. Working hours are paid at normal rates. Overtime: Hours worked over and above the required working hours. Overtime hours are negotiated to a maximum of 10 hours per week. Overtime is paid at a higher rate than ordinary working hours.',
    'q8-1': 'Infrastructure. Education. Capacity building. Health. Sanitation. Guest contributions.',
    'q8-2': 'Economic pillar / profit. Environmental pillar / planet.',
    'q8-3': 'Local residents are employed by the tourism business. The tourism business buys supplies locally or makes use of local services. The business procures goods and services from certified Fair Trade Tourism companies.',
    'q8-4': 'It encourage tourists to choose the services of tourism businesses that have been FTT certified. It assures tourists that the money that they spend at these establishments will benefit the local community. It shows other tourism businesses that tourists prefer to support FTT certified establishments. FTT certified companies collaborate to compile and market packages which will appeal to responsible tourists.',
    'q9-1-1': 'northern',
    'q9-1-2': 'Higher fuel price / Higher petrol price / Increase in the price of crude oil. Limited supply of wheat / Availability of wheat flour / Increase in bread prices.',
    'q9-1-3': 'Increased petrol prices will make long distance travel expensive and unaffordable. Car hire will be a less popular option because of the cost of petrol. Bus/shuttle/taxi industry will suffer – higher ticket prices and availability of fuel. Availability, frequency cancellations and increased cost of flights and other forms of transport will be affect.',
    'q9-2-1': 'Gauteng. Western Cape. Mpumalanga.',
    'q9-2-2': 'Long travel distances from the major gateways of the country. Limited air access/Fewer domestic flights to these provinces. These are lesser-known and marketed provinces. Limited infrastructure to attract major events. Within the province the attractions are situated far apart from each other.',
    'q10-1': 'The survey will help identify where and how he can improve his business and increase visitor numbers. To get a benchmark for incentives for staff. To get a sense of how customers regard his business.',
    'q10-2': 'Chef and the team',
    'q10-3': 'The ratings for the chef and the team were the highest. The conduct and communication involving frontline staff received low ratings from the customers. The cleanliness and maintenance of the restaurant received low ratings. The waiters do not take their work seriously.',
    'q10-4': 'Re-train and up-skill all frontline staff. Managers to effectively manage and control staff. Make the incentive package attractive to staff. Make a supervisor responsible to control the cleanliness and maintenance of the restaurant. Do everything in his power to create a memorable experience for guests.'
};

const normalizeAnswer = (answer) => {
    return answer
        .trim()
        .toLowerCase()
        .replace(/\s+/g, ' ')
        .replace(/[^a-z0-9=.\-<>/]/g, '');
};

const isAnswerCorrect = (questionId, answer) => {
    if (!answer) return false;
    const normalized = normalizeAnswer(answer);
    const correctAnswers = answerKey[questionId] || [];
    return correctAnswers.some(correct => normalizeAnswer(correct) === normalized);
};

const Header = () => (
    <header className="text-center border-b-4 border-double border-gray-800 pb-5 mb-7">
        <h1 className="text-3xl font-bold uppercase mb-2">National Senior Certificate</h1>
        <h2 className="text-2xl mb-1">Grade 12</h2>
        <h2 className="text-2xl mb-1">Tourism</h2>
        <h2 className="text-2xl mb-1">November 2022</h2>
        <p className="text-xl font-bold mb-1">Marks: 200</p>
        <p className="text-xl font-bold mb-1">Time: 3 hours</p>
        <p className="text-xl font-bold">This question paper consists of 23 pages.</p>
    </header>
);

const Instructions = () => (
    <section className="mb-10 break-before-page">
        <h2 className="text-2xl font-bold border-b-2 border-gray-800 pb-2 mb-4">Instructions and Information</h2>
        <p className="mb-4">Read the instructions carefully before answering the questions.</p>
        <ol className="list-decimal ml-8 mb-4">
            {[
                'This question paper consists of FIVE sections.',
                'Answer ALL the questions.',
                'Start EACH question on a NEW page.',
                'In QUESTION 3.1, round off your answers to TWO decimal places.',
                'Show ALL calculations.',
                'You may use a non-programmable calculator.',
                'Use the mark allocation of each question as a guide to the length of your answer.',
                'Write neatly and legibly.',
                'The table below is a guide to help you allocate your time according to each section.'
            ].map((item, index) => (
                <li key={index} className="mb-2">{item}</li>
            ))}
        </ol>
        <table className="w-full border-collapse border border-gray-800 mb-4">
            <tr>
                <th className="border border-gray-800 p-2 bg-gray-200 font-bold">SECTION</th>
                <th className="border border-gray-800 p-2 bg-gray-200 font-bold">TOPICS</th>
                <th className="border border-gray-800 p-2 bg-gray-200 font-bold">MARKS</th>
                <th className="border border-gray-800 p-2 bg-gray-200 font-bold">TIME (minutes)</th>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2">A</td>
                <td className="border border-gray-800 p-2">Short Questions</td>
                <td className="border border-gray-800 p-2">40</td>
                <td className="border border-gray-800 p-2">20</td>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2">B</td>
                <td className="border border-gray-800 p-2">Map Work and Tour Planning; Foreign Exchange</td>
                <td className="border border-gray-800 p-2">50</td>
                <td className="border border-gray-800 p-2">50</td>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2">C</td>
                <td className="border border-gray-800 p-2">Tourism Attractions; Culture and Heritage Tourism; Marketing</td>
                <td className="border border-gray-800 p-2">50</td>
                <td className="border border-gray-800 p-2">50</td>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2">D</td>
                <td className="border border-gray-800 p-2">Tourism Sectors; Sustainable and Responsible Tourism</td>
                <td className="border border-gray-800 p-2">30</td>
                <td className="border border-gray-800 p-2">30</td>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2">E</td>
                <td className="border border-gray-800 p-2">Domestic, Regional and International Tourism; Communication and Customer Care</td>
                <td className="border border-gray-800 p-2">30</td>
                <td className="border border-gray-800 p-2">30</td>
            </tr>
            <tr>
                <td className="border border-gray-800 p-2" colSpan="2">TOTAL</td>
                <td className="border border-gray-800 p-2">200</td>
                <td className="border border-gray-800 p-2">180</td>
            </tr>
        </table>
    </section>
);

const Question = ({ id, questionNumber, questionText, options, isTextInput = true, marks, table }) => {
    const [answer, setAnswer] = useState('');
    const [isCorrect, setIsCorrect] = useState(null);
    const [showAnswer, setShowAnswer] = useState(false);
    const [showSolution, setShowSolution] = useState(false);
    const [isDisabled, setIsDisabled] = useState(false);

    const handleSubmit = () => {
        setIsCorrect(isAnswerCorrect(id, answer));
        setIsDisabled(true);
    };

    return (
        <div className="mb-7 ml-6">
            <p className="mb-2">{questionText}</p>
            {options && (
                <ul className="list-disc ml-8 mb-4">
                    {options.map((option, index) => (
                        <li key={index} className="mb-1">{option}</li>
                    ))}
                </ul>
            )}
            {table && (
                <table className="w-full border-collapse border border-gray-800 mb-4">
                    {table.map((row, rowIndex) => (
                        <tr key={rowIndex}>
                            {row.map((cell, cellIndex) => (
                                <td key={cellIndex} className={`border border-gray-800 p-2 ${rowIndex === 0 ? 'bg-gray-200 font-bold' : ''}`}>
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </table>
            )}
            <div className="mb-5">
                {isTextInput ? (
                    <input
                        type="text"
                        id={id}
                        className={`w-full max-w-xs p-2 border border-gray-800 rounded font-serif text-base ${isCorrect === true ? 'border-green-600 bg-green-50' : isCorrect === false ? 'border-red-600 bg-red-50' : ''}`}
                        placeholder={`Answer Here ${options ? 'e.g., B' : ''}`}
                        value={answer}
                        onChange={(e) => setAnswer(e.target.value)}
                        disabled={isDisabled}
                    />
                ) : (
                    <textarea
                        id={id}
                        className={`w-full min-h-[80px] p-2 border border-gray-800 rounded font-serif text-base resize-y ${isCorrect === true ? 'border-green-600 bg-green-50' : isCorrect === false ? 'border-red-600 bg-red-50' : ''}`}
                        placeholder="Write your answer here..."
                        value={answer}
                        onChange={(e) => setAnswer(e.target.value)}
                        disabled={isDisabled}
                    />
                )}
            </div>
            {isDisabled && (
                <div className="flex gap-2 mb-4">
                    <button
                        className="px-4 py-2 bg-blue-600 text-white rounded font-serif text-sm hover:bg-blue-800 transition"
                        onClick={() => setShowAnswer(true)}
                    >
                        View Answer
                    </button>
                    <button
                        className="px-4 py-2 bg-blue-600 text-white rounded font-serif text-sm hover:bg-blue-800 transition"
                        onClick={() => setShowSolution(true)}
                    >
                        View Solution
                    </button>
                </div>
            )}
            {showAnswer && (
                <div className="mt-2 p-3 bg-green-50 border-l-4 border-green-600 rounded font-serif text-base">
                    <strong>Correct Answer:</strong> {answerKey[id]?.[0] || 'No answer available'}
                </div>
            )}
            {showSolution && (
                <div className="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center z-50">
                    <div className="bg-white p-7 rounded-lg max-w-2xl w-11/12 max-h-[80vh] overflow-y-auto font-serif text-base shadow-lg">
                        <h3 className="text-xl font-bold border-b-2 border-gray-200 pb-2 mb-4">Step-by-Step Solution</h3>
                        <p className="whitespace-pre-wrap">{solutions[id] || 'Solution not available for this question'}</p>
                        <button
                            className="mt-5 px-5 py-2 bg-blue-600 text-white rounded font-serif text-base hover:bg-blue-800 transition"
                            onClick={() => setShowSolution(false)}
                        >
                            Close
                        </button>
                    </div>
                </div>
            )}
            {marks && <p className="mt-2">({marks})</p>}
        </div>
    );
};

const SectionA = () => (
    <section id="section-a" className="mb-10 break-before-page">
        <h2 className="text-2xl font-bold border-b-2 border-gray-800 pb-2 mb-4">SECTION A: SHORT QUESTIONS</h2>
        <h3 className="text-xl font-bold mb-4">QUESTION 1</h3>
        <div className="mb-7">
            <p>1.1 Various options are provided as possible answers to the following questions. Choose the answer and write only the letter (A–D) next to the question numbers (1.1.1 to 1.1.20) in the ANSWER BOOK, e.g. 1.1.21 D.</p>
            <Question
                id="q1-1-1"
                questionNumber="1.1.1"
                questionText="A recent Covid-19 requirement for international travel:"
                options={['A Visa application', 'B Proof of vaccination', 'C Cholera certificate', 'D International driver\'s licence']}
            />
            <Question
                id="q1-1-2"
                questionNumber="1.1.2"
                questionText="Ms Jones purchased jewellery to the value of R50 000 on a recent overseas trip. On arrival at South African customs, this purchase would fall under …"
                options={['A items to be declared.', 'B items not to be declared.', 'C duty-free allowances.', 'D prohibited items.']}
            />
            <Question
                id="q1-1-3"
                questionNumber="1.1.3"
                questionText="Sydney (+10) is … hours ahead of Johannesburg (+2)."
                options={['A 0', 'B 9', 'C 8', 'D 6']}
            />
            <Question
                id="q1-1-4"
                questionNumber="1.1.4"
                questionText="Jet fatigue is a travel-related condition caused by travelling …"
                options={['A across many time zones.', 'B on a long-haul flight.', 'C at odd times of the day.', 'D only at night']}
            />
            <Question
                id="q1-1-5"
                questionNumber="1.1.5"
                questionText="The bank selling rate is always … the bank buying rate."
                options={['A lower than', 'B higher than', 'C equal to', 'D double']}
            />
            <Question
                id="q1-1-6"
                questionNumber="1.1.6"
                questionText="The famous wall in Israel used for prayers and confessions:"
                options={['A Berlin Wall', 'B Southern Wall', 'C Wailing Wall', 'D Eastern Wall']}
            />
            <Question
                id="q1-1-7"
                questionNumber="1.1.7"
                questionText="Petra is located in this Middle Eastern country:"
                options={['A Israel', 'B Jordan', 'C Lebanon', 'D Turkey']}
            />
            <Question
                id="q1-1-8"
                questionNumber="1.1.8"
                questionText="The Swiss Alps are known as …"
                options={['A a sacred mountain range for locals.', 'B a range of mountains in Nepal.', 'C a mountain range popular for skiing holidays.', 'D the highest mountain range in the world.']}
            />
            <Question
                id="q1-1-9"
                questionNumber="1.1.9"
                questionText="The Vredefort Dome and iSimangaliso Wetland Park have the following in common:"
                options={['A Both are located in KwaZulu-Natal.', 'B Both are natural sites.', 'C Both are cultural sites.', 'D Both are located in North West.']}
            />
            <Question
                id="q1-1-10"
                questionNumber="1.1.10"
                questionText="The current brand image of South Africa:"
                options={['A [Image A]', 'B [Image B]', 'C [Image C]', 'D [Image D]']}
            />
            <Question
                id="q1-1-11"
                questionNumber="1.1.11"
                questionText="Guidelines regulating uniforms and other clothing to be worn during working hours:"
                options={['A Dress code', 'B Media policy', 'C Packing policy', 'D Currency code']}
            />
            <Question
                id="q1-1-12"
                questionNumber="1.1.12"
                questionText="A basic condition of employment included in a contract of employment:"
                options={['A Financial challenges', 'B Product packaging', 'C Names of businesses', 'D Core duties']}
            />
            <Question
                id="q1-1-13"
                questionNumber="1.1.13"
                questionText="Many responsible tourism businesses adopt a pledge that will …"
                options={['A maximise the negative effects of crime.', 'B decrease the benefits from tourist visits.', 'C increase poaching in a protected area.', 'D minimise the impact on the environment.']}
            />
            <Question
                id="q1-1-14"
                questionNumber="1.1.14"
                questionText="Airline staff receive flight tickets at a discounted rate as a/an …"
                options={['A travel benefit.', 'B urban legend.', 'C mystery client.', 'D customs requirement.']}
            />
            <Question
                id="q1-1-15"
                questionNumber="1.1.15"
                questionText="A sustainable practice when a lodge is built in an environmentally sensitive area:"
                options={['A Trees are chopped down to build the lodge.', 'B Bricks are imported from a foreign country.', 'C Large areas are cleared to build the lodge.', 'D Wooden walkways are built around existing trees.']}
            />
            <Question
                id="q1-1-16"
                questionNumber="1.1.16"
                questionText="The G20 (Group of Twenty) gathering that took place in Bali, Indonesia, in November 2022, is an example of a/an …"
                options={['A global summit.', 'B local occurrence.', 'C political situation.', 'D unforeseen occurrence.']}
            />
            <Question
                id="q1-1-17"
                questionNumber="1.1.17"
                questionText="… is not a safe payment option when travelling internationally."
                options={['A A Diners Club debit card', 'B An EFT electronic payment card', 'C Carrying large amounts of cash', 'D A pre-loaded foreign exchange debit card']}
            />
            <Question
                id="q1-1-18"
                questionNumber="1.1.18"
                questionText="An example of a political situation that can impact on tourism:"
                options={['A Diseases', 'B Earthquakes', 'C Tsunamis', 'D Civil wars']}
                marks="20 x 1 (20)"
            />
        </div>
        {/* Continue with 1.2, 1.3, 1.4, 1.5 as in the initial code */}
        {/* ... */}
        <p className="font-bold">TOTAL SECTION A: 40</p>
    </section>
);

// Add SectionB, SectionC, SectionD, SectionE similarly, based on the transcribed content from images.

const Footer = () => (
    <footer className="text-center mt-10 border-t-4 border-double border-gray-800 pt-5">
        <p className="text-xl font-bold">GRAND TOTAL: 200</p>
    </footer>
);

const LifeScienceP2Nov2022Eng = () => {
    const [answers, setAnswers] = useState({});
    const [score, setScore] = useState(null);
    const [correctCount, setCorrectCount] = useState(0);
    const [totalQuestions, setTotalQuestions] = useState(0);

    const handleSubmit = () => {
        let correct = 0;
        let total = 0;
        Object.keys(answers).forEach(id => {
            total++;
            if (isAnswerCorrect(id, answers[id])) {
                correct++;
            }
        });
        setCorrectCount(correct);
        setTotalQuestions(total);
        const percentage = total ? Math.round((correct / total) * 100) : 0;
        setScore(percentage);
    };

    return (
        <div className="font-serif text-gray-900 bg-gray-50 max-w-4xl mx-auto p-7 box-border">
            <Header />
            <Instructions />
            <SectionA />
            {/* <SectionB /> */}
            {/* <SectionC /> */}
            {/* <SectionD /> */}
            {/* <SectionE /> */}
            <Footer />
            <div className="mt-7 text-center">
                <button
                    className="px-6 py-3 bg-blue-600 text-white rounded font-serif text-base hover:bg-blue-800 transition disabled:bg-gray-400 disabled:cursor-not-allowed"
                    onClick={handleSubmit}
                    disabled={score !== null}
                >
                    Submit Answers
                </button>
                {score !== null && (
                    <div className="mt-7 p-6 rounded-lg bg-gray-200 border border-gray-400 shadow">
                        <h3 className="text-2xl font-bold mb-4">Your Score: {score}%</h3>
                        <p className="mb-4">{`(${correctCount} out of ${totalQuestions} correct)`}</p>
                        <p className={`font-bold ${score >= 50 ? 'text-green-600' : 'text-red-600'}`}>
                            {score >= 50 ? 'Excellent work! You\'ve passed!' : 'Keep practicing! You\'ll improve!'}
                        </p>
                        <div className="flex justify-center gap-4 mt-5">
                            <button
                                className="px-5 py-2 bg-green-600 text-white rounded font-serif text-base hover:bg-green-800 transition"
                                onClick={() => window.location.reload()}
                            >
                                Retry Exam
                            </button>
                            <button
                                className="px-5 py-2 bg-red-600 text-white rounded font-serif text-base hover:bg-red-800 transition"
                                onClick={() => window.close()}
                            >
                                Exit
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default LifeScienceP2Nov2022Eng